import { NextResponse } from "next/server";

import { getSession, hasPermission, PERMISSIONS } from "@/lib/auth";
import { DEFAULT_NOTIFY_INBOX } from "@/lib/email/resolve-notify-inbox";
import { sendResendEmail } from "@/lib/email/send-resend-email";
import { getQuestionnaireI18n } from "@/lib/questionnaire-i18n";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** Probni email iz admin panela — isti Resend pipeline kao kontakt forma. */
export async function POST(): Promise<NextResponse> {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ ok: false, error: "Niste prijavljeni." }, { status: 401 });
  }
  if (!hasPermission(session.role, PERMISSIONS.SITE_CONTENT_MANAGE)) {
    return NextResponse.json({ ok: false, error: "Nemate dozvolu." }, { status: 403 });
  }

  const t = getQuestionnaireI18n("me");
  const to = process.env.UPITNIK_NOTIFY_EMAIL?.trim() || DEFAULT_NOTIFY_INBOX;
  const now = new Date().toLocaleString("sr-ME", { timeZone: "Europe/Podgorica" });

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
  <body style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;padding:20px;color:#1a1a1a;background:#fff">
    <div style="background:#e8682a;color:#fff;padding:18px 24px;border-radius:8px;margin-bottom:20px">
      <h1 style="margin:0;font-size:18px">${t.email.emailTitle} — TEST</h1>
      <p style="margin:6px 0 0;font-size:13px;opacity:0.85">${t.email.receivedAt} ${now}</p>
    </div>
    <p style="font-size:14px;line-height:1.6">Ovo je <strong>probna poruka</strong> poslata iz admin panela.</p>
    <p style="font-size:14px;line-height:1.6">Ako vidite ovu poruku — email pipeline radi ispravno i pacijenti će uspešno slati upitnik.</p>
    <hr style="margin-top:24px;border:1px solid #f0e6dc">
    <p style="font-size:11px;color:#999;margin-top:8px">${t.email.autoGenerated}</p>
  </body></html>`;

  const result = await sendResendEmail({
    to,
    subject: `${t.email.subjectPrefix} TEST iz admin panela — ${new Date().toLocaleDateString("sr-ME")}`,
    text: "Test poruka iz admin panela. Email pipeline radi.",
    html,
    logPrefix: "[upitnik-admin-test]",
  });

  if (result.ok) {
    return NextResponse.json({
      ok: true,
      to,
      resendId: result.resendId ?? null,
    });
  }

  if (result.code === "missing_api_key") {
    return NextResponse.json(
      {
        ok: false,
        error: "RESEND_API_KEY nije postavljen na serveru.",
        code: result.code,
      },
      { status: 502 },
    );
  }

  return NextResponse.json(
    {
      ok: false,
      error: "Resend API je odbio poruku.",
      code: result.code,
      status: result.status,
      detail: result.bodySnippet,
      to,
    },
    { status: 502 },
  );
}
