/**
 * Sve labele i tekstovi za upitnik (`/[locale]/upitnik`).
 *
 * Slobodno mijenjajte tekstove ovde — promjene se odmah vide na sajtu
 * i u emailu koji prima klinika.
 *
 * Strukturu (ključeve) NE mijenjajte — samo tekstove sa desne strane.
 *
 * Ako neki prevod (en/ru) ne unesete, fallback je crnogorski (me).
 */

import type { Locale } from "@/lib/i18n";

export type QuestionnaireI18n = {
  /* Hero sekcija stranice */
  page: {
    eyebrow: string;
    title: string;
    intro: string;
    confidential: string;
  };
  /* Zajedničke UI riječi */
  ui: {
    yes: string;
    no: string;
    submit: string;
    submitting: string;
    addRow: string;
    successTitle: string;
    successText: string;
    errorText: string;
    consent: string;
    progress: string;          /* npr "{done} / {total} sekcija popunjeno" */
    requiredHint: string;      /* "* obavezna polja" */
    optional: string;
  };
  /* Naslovi sekcija */
  sections: {
    s1: string;
    s2: string;
    s3a: string;
    s3b: string;
    s3c: string;
    s3d: string;
    s3e: string;
    s3f: string;
    s3g: string;
    s3h: string;
    s3i: string;
    s3j: string;
    s3k: string;
    s3l: string;
    s4a: string;
    s4b: string;
    s4c: string;
    s4d: string;
    s4e: string;
    s4f: string;
    s4g: string;
    malePartnerDivider: string;
  };
  /* Pod-naslovi i grupne oznake */
  groups: {
    femalePartner: string;
    malePartner: string;
    asCouple: string;
    detailsTreatments: string;
    operations: string;
    presentDiseases: string;
    fertilityCheckups: string;
    treatmentDetails: string;
    diagnosed: string;
    details: string;
    typeOfReaction: string;
  };
  /* Sve labele polja, pitanja, opcije */
  f: Record<string, string>;
  /* Opcije za odabire (radio/dugmad) */
  opts: {
    married: string;
    unmarried: string;
    email: string;
    phoneViber: string;
    bothComm: string;
    positive: string;
    negative: string;
    maleFactor: string;
    femaleFactor: string;
    bothFactor: string;
  };
  /* Bolesti — moraju ostati ovim redom, jer se koriste kao ključevi */
  diseases: string[];
  /* Email — formatiranje subject-a i naslova */
  email: {
    subjectPrefix: string;       /* "[Upitnik]" */
    emailTitle: string;          /* "Upitnik za pacijente — Human Reproduction Center" */
    receivedAt: string;          /* "Primljeno:" */
    notAnswered: string;
    notEntered: string;
    none: string;
    autoGenerated: string;
    patientSubject: string;
    patientGreeting: string;     /* "Poštovani/a {name}," */
    patientFallbackName: string;
    patientBody: string;
    patientSignoff: string;
  };
};

// ───────────────────────────────────────────────────────────────────────
// MONTENEGRIN (default)
// ───────────────────────────────────────────────────────────────────────
const ME: QuestionnaireI18n = {
  page: {
    eyebrow: "Human Reproduction Center",
    title: "Upitnik za pacijente",
    intro:
      "Popunjavanjem ovog upitnika pomažete našem timu da se bolje upozna sa Vašim slučajem i uvidi pojedinosti koje mogu pomoći u odabiru pravog tretmana za Vas.",
    confidential: "Svi podaci se tretiraju kao strogo povjerljivi",
  },
  ui: {
    yes: "Da",
    no: "Ne",
    submit: "Pošalji upitnik",
    submitting: "Slanje u toku...",
    addRow: "Dodaj red",
    successTitle: "Upitnik je uspješno poslan!",
    successText:
      "Naš tim je primio Vaše odgovore i kontaktiraće Vas u najkraćem mogućem roku. Hvala!",
    errorText: "Došlo je do greške. Molimo pokušajte ponovo ili nas kontaktirajte.",
    consent:
      "Popunjavanjem i slanjem ovog upitnika pomažete nam da se bolje upoznamo sa Vašim slučajem i pružimo Vam najbolju moguću pomoć. Hvala!",
    progress: "{done} / {total} sekcija popunjeno",
    requiredHint: "* označava obavezna polja",
    optional: "(opcionalno)",
  },
  sections: {
    s1: "DIO 1 — Informacije o pacijentu",
    s2: "DIO 2 — Istorija fertilnosti para",
    s3a: "DIO 3a — Ženski partner: Opšte informacije",
    s3b: "DIO 3b — Menstrualni ciklusi",
    s3c: "DIO 3c — Ginekološka istorija",
    s3d: "DIO 3d — Prethodne trudnoće",
    s3e: "DIO 3e — Prethodni ART tretmani",
    s3f: "DIO 3f — Seksualni odnosi i SPB",
    s3g: "DIO 3g — Trenutna terapija",
    s3h: "DIO 3h — Alergije",
    s3i: "DIO 3i — Zdravstveni problemi",
    s3j: "DIO 3j — Hirurški zahvati",
    s3k: "DIO 3k — Porodična istorija bolesti",
    s3l: "DIO 3l — Životne navike",
    s4a: "DIO 4a — Muški partner: Opšte informacije",
    s4b: "DIO 4b — Reproduktivna istorija",
    s4c: "DIO 4c — Seksualni odnosi i SPB",
    s4d: "DIO 4d — Trenutna terapija",
    s4e: "DIO 4e — Alergije",
    s4f: "DIO 4f — Zdravstveni problemi i hirurgija",
    s4g: "DIO 4g — Životne navike",
    malePartnerDivider: "Muški partner",
  },
  groups: {
    femalePartner: "Ženski partner",
    malePartner: "Muški partner",
    asCouple: "Kao par",
    detailsTreatments: "Detalji o tretmanima",
    operations: "Operacije",
    presentDiseases: "Označite prisutna oboljenja",
    fertilityCheckups: "Unesite rezultate i datume ispitivanja",
    treatmentDetails: "Detalji",
    diagnosed: "Označite ako ste bili dijagnostikovani",
    details: "Detalji",
    typeOfReaction: "Tip reakcije",
  },
  f: {
    fullName: "Puno ime (ime i prezime)",
    dob: "Datum rođenja",
    passport: "Br. pasoša / lične karte / datum isteka",
    email: "Email adresa",
    phone: "Broj mobilnog telefona",
    occupation: "Zanimanje",
    maritalStatus: "Bračni status",
    country: "Država prebivališta",
    prefComm: "Preferirani način komunikacije",
    mainContact: "Glavna osoba za kontakt",
    relYears: "Koliko dugo ste u vezi/braku? (godine)",
    relMonths: "Koliko dugo ste u vezi/braku? (mjeseci)",
    pregInRel: "Da li ste ikada bili trudni tokom ove veze?",
    pregCount: "Koliko puta?",
    pregTerm: "Koliko završeno terminskim porođajem?",
    tryYears: "Koliko dugo pokušavate zatrudnjeti? (godine)",
    tryMonths: "Koliko dugo pokušavate zatrudnjeti? (mjeseci)",
    diagYn: "Da li vam je dato medicinsko objašnjenje za infertilitet?",
    diagFactor: "Faktor",
    diagText: "Dijagnoza",
    diagYear: "Godina dijagnoze",
    artYn: "Da li ste pokušavali ART (IUI, IVF)?",
    artDetails: "Kratko objasnite (tip tretmana, koje godine, koliko pokušaja, klinika)",
    frozenYn: "Da li imate zamrznuti materijal (embrioni, jajne ćelije, spermatozoidi)?",
    frozenDetails: "Navedite",
    frozenTransport: "Želite transportovati u našu kliniku?",

    age: "Starost (godine)",
    height: "Visina (cm)",
    weight: "Težina (kg)",
    bloodGroup: "Krvna grupa",
    rhFactor: "Rh faktor",
    fConcYn: "Da li imate problema sa začećem u ovom odnosu?",
    fConcDur: "Koliko dugo pokušavate (godina/Mjeseci)?",

    menarche: "Koliko godina ste imali kada je počela prva menstruacija?",
    cyclesYn: "Da li imate menstrualne cikluse?",
    cyclesRegular: "Da li su ciklusi redovni?",
    cycleDays: "Trajanje ciklusa (dana)",
    cycleMin: "Minimum (dana)",
    cycleMax: "Maksimum (dana)",
    bleedDays: "Koliko krvarenje obično traje? (dana)",
    interBleed: "Da li imate krvarenje između menstruacija?",
    bleedDesc: "Opišite krvarenje (obilno/crveno, počinje-prestaje naglo, braon/smeđe...)",
    painfulMens: "Da li su menstruacije bolne (dismenoreja)?",
    heavyMens: "Da li su menstruacije jako obilne (menoragija)?",
    clots: "Da li imate ugruške?",
    padsPerDay: "Koliko uložaka/tampona dnevno?",
    affectsLife: "Da li menstruacija utiče na dnevne aktivnosti?",
    lastMens: "Datum posljednje menstruacije (prvi dan)",

    secretionYn: "Da li imate vaginalni sekret?",
    secretionColor: "Boja sekreta",
    secretionSmell: "Da li ima miris (opišite)?",
    bleedAfterSex: "Da li krvarite nakon odnosa?",
    painSex: "Da li osjećate bol tokom odnosa?",
    papaYn: "Da li ste ranije radili Papa test?",
    papaDate: "Kada je bio posljednji?",
    papaRegular: "Da li je bio uredan?",
    papaAbnorm: "Da li ste ikada imali abnormalan Papa test?",
    cervixYn: "Da li ste imali intervenciju na grliću materice?",
    cervixWhen: "Kada?",
    cervixTreatment: "Koji tretman?",
    iudYn: "Da li ste ikada koristili spiralu?",
    iudDur: "Koliko dugo?",
    iudRemoved: "Kada je uklonjena?",
    ocpYn: "Da li ste koristili oralne kontraceptivne pilule?",
    ocpDur: "Koliko dugo?",
    ocpStopped: "Koliko vremena od prestanka?",
    endometriosis: "Endometrioza?",
    pcos: "PCOS/PMOS?",
    cysts: "Ovarijalne ciste?",
    fibroids: "Miomi?",
    polyps: "Endometrijalni polipi?",
    cancer: "Kancer (grlić, dojke, jajnici)?",
    gynekDetails: "Detalji o navedenim stanjima (endometrioza, PCOS, ciste, miomi, polipi...)",
    gynekOther: "Druga ginekološka stanja od značaja",

    everPregYn: "Da li ste ikada bile trudni?",
    pregDate: "Datum porođaja",
    pregPartner: "Sa trenutnim partnerom?",
    pregType: "Tip koncepcije + komplikacije",
    pregDelivery: "Tip porođaja (vaginalni/carski rez)",
    pregOutcome: "Ishod (živorođenje, mrtvorođenje, pobačaj, vanmaternična...)",
    pregNG: "Nedjelja gestacije (NG)",

    artYesYn: "Da li ste imali ART tretmane (IUI, IVF, ICSI, donacija jajnih ćelija/embriona)?",
    surrogateYn: "Da li ste učestvovali u surogat programima?",
    artDate: "Datum",
    artType: "Tip tretmana",
    artProtocol: "Protokol hormonske stimulacije",
    artEggs: "Broj dobijenih jajnih ćelija",
    artFert: "Broj oplođenih",
    artTransf: "Broj transf. embriona",
    artGenetic: "Genetski testirani?",
    artFrozen: "Broj zamrznutih embriona",
    artOutcome: "Ishod / bitni detalji",
    fertAnalysisYn: "Da li ste imali analize fertilnosti u zadnjih 3–6 mjeseci?",
    fertAnalysisHint: "Unesite rezultate i datume ispitivanja",
    fertResultHint: "rezultat, datum, laboratorija",
    fertExample: "npr. 5.2 mIU/L, 01.04.2025, Lab XY",

    sexProbYn: "Da li ste imali probleme tokom odnosa (bol, suvoća, nemogućnost vaginalnog odnosa)?",
    sexProbDetails: "Detalji",
    stiYn: "Da li ste ikada imali SPB/SPI (Chlamydia, Gonoreja, Herpes, Ureaplasma, Mycoplasma)?",
    stiDetails: "Koju i koja terapija?",
    hepB: "Hepatitis B",
    hepC: "Hepatitis C",
    hiv: "HIV",
    syph: "Sifilis",
    stiOther: "Detalji (ako je nešto označeno)",

    medsYn: "Da li koristite medikamente, vitamine, dodatke ishrani ili homeopatske lijekove?",
    medName: "Medikament",
    medDose: "Doza",
    medFreq: "Učestalost upotrebe",

    allergyMed: "Alergija na lijekove?",
    allergyLatex: "Alergija na lateks?",
    allergyAnesth: "Alergija na anestetike / nuspojave?",
    allergyDetails: "Detalji alergija i tip reakcije",

    seriousIllYn: "Da li ste bolovali od nekog ozbiljnog oboljenja?",
    seriousIllDetails: "Detalji",
    bruisingEasily: "Laka pojava hematoma?",
    bleedingStop: "Problem sa zaustavljanjem krvarenja?",

    gynekOpYn: "Da li ste imali ginekološku hirursku intervenciju?",
    otherOpYn: "Da li ste imali druge operacije (koje nisu ginekološke)?",
    opProcedure: "Procedura / intervencija",
    opDate: "Datum",
    opReason: "Razlog",
    opOutcome: "Ishod",

    geneticsYn: "Da li u Vašoj porodici postoje genetska ili nasljedna oboljenja?",
    geneticsDetails: "Koje bolesti i koji član porodice?",

    smoker: "Da li ste pušač?",
    cigarettesPerDay: "Koliko cigareta dnevno?",
    vaping: "Koristite li elektronske cigarete ili vejpove?",
    drugsYn: "Da li ste koristili droge ili psihoaktivne supstance u prethodnih 5 godina?",
    drugsDetails: "Koje?",
    alcohol: "Da li konzumirate alkohol?",
    alcoholDrinks: "Koliko pića nedeljno? (1 piće = 0.5l piva / čaša vina / čašica žestokog)",
    tattoosYn: "Da li imate tetovaže?",
    tattoosDetails: "Lokacija, godina i eventualne komplikacije",
    otherInfo: "Ostale informacije koje smatrate relevantnim",

    mPregYn: "Da li ste imali trudnoću sa trenutnom partnerkom?",
    mPregDetails: "Koliko trudnoća / koliko završeno terminskim porođajem?",
    mOtherPregYn: "Da li ste imali trudnoću s drugom partnerkom?",
    mOtherPregDetails: "Koliko trudnoća / završeno porođajem?",
    klomidYn: "Da li ste koristili lijek Klomid/Klomifen?",
    klomidDur: "Koliko dugo?",
    mArtYn: "Da li ste ranije radili testove infertiliteta ili ART (IUI, IVF, ICSI)?",
    mArtDetails: "Detalji",
    erectionYn: "Da li imate poteškoće s erekcijom, održavanjem erekcije ili ejakulacijom?",
    erectionDetails: "Detalji",
    testesYn: "Da li ste ikada imali nespuštene testise?",
    testesDetails: "Detalji",
    mumpsYn: "Da li ste imali zauške u djetinjstvu?",
    mumpsEffect: "Da li su imali uticaj na testise?",
    pubertyAge: "Koliko godina ste imali kada je počeo pubertet?",
    saunaYn: "Da li koristite tople kupke, saune ili jakuzi?",
    saunaDetails: "Koliko često i kada je bio posljednji put?",
    feverYn: "Da li ste u zadnjoj godini imali upalu s groznicom?",
    feverDetails: "Period i temperatura",
    steroidsYn: "Da li ste uzimali anaboličke steroide ili lijekove za bodibilding?",
    steroidsDetails: "Koje, koliko dugo i kada prestali?",

    sexFreq: "Koliko često imate seksualne odnose?",
    sexFreqExample: "npr. 2-3x nedeljno",

    mSurgeryYn: "Da li ste imali hirursku intervenciju?",

    mDrugsYn: "Da li ste koristili droge u prethodnih 5 godina?",
  },
  opts: {
    married: "U braku",
    unmarried: "Van braka",
    email: "Email",
    phoneViber: "Telefon/Viber",
    bothComm: "Oboje",
    positive: "Pozitivan",
    negative: "Negativan",
    maleFactor: "Muški faktor",
    femaleFactor: "Ženski faktor",
    bothFactor: "Oboje",
  },
  diseases: [
    "Diabetes",
    "Astma",
    "Tuberkuloza",
    "Aritmije",
    "Bol u grudima",
    "Povišen krvni pritisak",
    "Bolesti štitne žlijezde / endokrini poremećaji",
    "Kongenitalne bolesti",
    "Psihijatrijsko stanje / depresija",
    "Oboljenja jetre",
    "Gastrointestinalni problemi",
    "Oboljenja bubrega",
    "Kancer (hemio/radioterapija)",
    "Reumatoidni artritis",
    "Imunološki problemi",
    "Neurološki problemi",
    "Problem sa koagulacijom/ugrušcima",
    "Druge infekcije",
    "Izloženost radioaktivnim / toksičnim supstancama",
  ],
  email: {
    subjectPrefix: "[Upitnik]",
    emailTitle: "Upitnik za pacijente — Human Reproduction Center",
    receivedAt: "Primljeno:",
    notAnswered: "nije odgovoreno",
    notEntered: "nije uneseno",
    none: "Nijedno",
    autoGenerated: "Automatski generisano sa humanreproduction.com/upitnik",
    patientSubject: "Potvrda — upitnik primljen | Human Reproduction Center",
    patientGreeting: "Poštovani/a {name},",
    patientFallbackName: "pacijente",
    patientBody:
      "Primili smo Vaš upitnik. Naš tim će pregledati odgovore i kontaktirati Vas u najkraćem mogućem roku.",
    patientSignoff: "Hvala Vam na povjerenju.",
  },
};

// ───────────────────────────────────────────────────────────────────────
// ENGLISH
// ───────────────────────────────────────────────────────────────────────
const EN: QuestionnaireI18n = {
  page: {
    eyebrow: "Human Reproduction Center",
    title: "Patient Questionnaire",
    intro:
      "By completing this questionnaire, you help our team better understand your case and identify details that may assist in choosing the right treatment for you.",
    confidential: "All information is treated as strictly confidential",
  },
  ui: {
    yes: "Yes",
    no: "No",
    submit: "Submit questionnaire",
    submitting: "Sending...",
    addRow: "Add row",
    successTitle: "Questionnaire successfully submitted!",
    successText:
      "Our team has received your answers and will contact you as soon as possible. Thank you!",
    errorText: "An error occurred. Please try again or contact us.",
    consent:
      "By completing and submitting this questionnaire you help us better understand your case and provide the best possible care. Thank you!",
    progress: "{done} / {total} sections completed",
    requiredHint: "* indicates required fields",
    optional: "(optional)",
  },
  sections: {
    s1: "PART 1 — Patient information",
    s2: "PART 2 — Couple's fertility history",
    s3a: "PART 3a — Female partner: General information",
    s3b: "PART 3b — Menstrual cycles",
    s3c: "PART 3c — Gynecological history",
    s3d: "PART 3d — Previous pregnancies",
    s3e: "PART 3e — Previous ART treatments",
    s3f: "PART 3f — Sexual relations & STIs",
    s3g: "PART 3g — Current therapy",
    s3h: "PART 3h — Allergies",
    s3i: "PART 3i — Health problems",
    s3j: "PART 3j — Surgical history",
    s3k: "PART 3k — Family medical history",
    s3l: "PART 3l — Lifestyle",
    s4a: "PART 4a — Male partner: General information",
    s4b: "PART 4b — Reproductive history",
    s4c: "PART 4c — Sexual relations & STIs",
    s4d: "PART 4d — Current therapy",
    s4e: "PART 4e — Allergies",
    s4f: "PART 4f — Health problems & surgery",
    s4g: "PART 4g — Lifestyle",
    malePartnerDivider: "Male partner",
  },
  groups: {
    femalePartner: "Female partner",
    malePartner: "Male partner",
    asCouple: "As a couple",
    detailsTreatments: "Treatment details",
    operations: "Operations",
    presentDiseases: "Check any present conditions",
    fertilityCheckups: "Enter test results and dates",
    treatmentDetails: "Details",
    diagnosed: "Tick if you have been diagnosed",
    details: "Details",
    typeOfReaction: "Type of reaction",
  },
  f: {
    fullName: "Full name (first & last)",
    dob: "Date of birth",
    passport: "Passport / ID number / expiry date",
    email: "Email address",
    phone: "Mobile phone number",
    occupation: "Occupation",
    maritalStatus: "Marital status",
    country: "Country of residence",
    prefComm: "Preferred communication channel",
    mainContact: "Main contact person",
    relYears: "How long have you been in a relationship/married? (years)",
    relMonths: "How long have you been in a relationship/married? (months)",
    pregInRel: "Have you ever been pregnant during this relationship?",
    pregCount: "How many times?",
    pregTerm: "How many ended in full-term delivery?",
    tryYears: "How long have you been trying to conceive? (years)",
    tryMonths: "How long have you been trying to conceive? (months)",
    diagYn: "Have you ever been given a medical explanation for infertility?",
    diagFactor: "Factor",
    diagText: "Diagnosis",
    diagYear: "Year of diagnosis",
    artYn: "Have you attempted ART (IUI, IVF)?",
    artDetails: "Briefly explain (type, year, attempts, clinic)",
    frozenYn: "Do you have frozen material (embryos, eggs, sperm)?",
    frozenDetails: "Please specify",
    frozenTransport: "Would you like to transfer it to our clinic?",

    age: "Age (years)",
    height: "Height (cm)",
    weight: "Weight (kg)",
    bloodGroup: "Blood group",
    rhFactor: "Rh factor",
    fConcYn: "Have you had problems conceiving in this relationship?",
    fConcDur: "How long have you been trying (years/months)?",

    menarche: "How old were you at your first menstruation?",
    cyclesYn: "Do you have menstrual cycles?",
    cyclesRegular: "Are your cycles regular?",
    cycleDays: "Cycle length (days)",
    cycleMin: "Minimum (days)",
    cycleMax: "Maximum (days)",
    bleedDays: "How long does bleeding usually last? (days)",
    interBleed: "Do you have bleeding between periods?",
    bleedDesc: "Describe the bleeding (heavy/red, sudden start–stop, brown spotting...)",
    painfulMens: "Are your periods painful (dysmenorrhea)?",
    heavyMens: "Are your periods very heavy (menorrhagia)?",
    clots: "Do you have clots?",
    padsPerDay: "How many pads/tampons per day?",
    affectsLife: "Does menstruation affect your daily activities?",
    lastMens: "Date of last menstruation (first day)",

    secretionYn: "Do you have vaginal discharge?",
    secretionColor: "Discharge color",
    secretionSmell: "Does it have an odor (please describe)?",
    bleedAfterSex: "Do you bleed after intercourse?",
    painSex: "Do you feel pain during intercourse?",
    papaYn: "Have you had a Pap test before?",
    papaDate: "When was the last one?",
    papaRegular: "Was it normal?",
    papaAbnorm: "Have you ever had an abnormal Pap test?",
    cervixYn: "Have you had any procedure on the cervix?",
    cervixWhen: "When?",
    cervixTreatment: "Which treatment?",
    iudYn: "Have you ever used an IUD?",
    iudDur: "How long?",
    iudRemoved: "When was it removed?",
    ocpYn: "Have you used oral contraceptive pills?",
    ocpDur: "How long?",
    ocpStopped: "How long since stopping?",
    endometriosis: "Endometriosis?",
    pcos: "PCOS/PMOS?",
    cysts: "Ovarian cysts?",
    fibroids: "Fibroids?",
    polyps: "Endometrial polyps?",
    cancer: "Cancer (cervix, breast, ovary)?",
    gynekDetails: "Details about above conditions (endometriosis, PCOS, cysts, fibroids, polyps...)",
    gynekOther: "Other significant gynecological conditions",

    everPregYn: "Have you ever been pregnant?",
    pregDate: "Delivery date",
    pregPartner: "With current partner?",
    pregType: "Conception type + complications",
    pregDelivery: "Delivery type (vaginal/C-section)",
    pregOutcome: "Outcome (live birth, stillbirth, miscarriage, ectopic...)",
    pregNG: "Gestational weeks (GW)",

    artYesYn: "Have you had ART treatments (IUI, IVF, ICSI, egg/embryo donation)?",
    surrogateYn: "Have you participated in surrogacy programs?",
    artDate: "Date",
    artType: "Treatment type",
    artProtocol: "Hormone stimulation protocol",
    artEggs: "Number of retrieved eggs",
    artFert: "Number fertilized",
    artTransf: "Embryos transferred",
    artGenetic: "Genetically tested?",
    artFrozen: "Number of frozen embryos",
    artOutcome: "Outcome / important details",
    fertAnalysisYn: "Have you had fertility tests in the last 3–6 months?",
    fertAnalysisHint: "Enter results and test dates",
    fertResultHint: "result, date, lab",
    fertExample: "e.g. 5.2 mIU/L, 04/01/2025, Lab XY",

    sexProbYn: "Have you had problems during intercourse (pain, dryness, inability to have vaginal sex)?",
    sexProbDetails: "Details",
    stiYn: "Have you ever had an STI (Chlamydia, Gonorrhea, Herpes, Ureaplasma, Mycoplasma)?",
    stiDetails: "Which and which therapy?",
    hepB: "Hepatitis B",
    hepC: "Hepatitis C",
    hiv: "HIV",
    syph: "Syphilis",
    stiOther: "Details (if anything marked)",

    medsYn: "Are you taking any medication, vitamins, supplements or homeopathic remedies?",
    medName: "Medication",
    medDose: "Dose",
    medFreq: "Frequency of use",

    allergyMed: "Allergy to medication?",
    allergyLatex: "Allergy to latex?",
    allergyAnesth: "Allergy/reaction to anesthetics?",
    allergyDetails: "Details and type of reaction",

    seriousIllYn: "Have you suffered from any serious illness?",
    seriousIllDetails: "Details",
    bruisingEasily: "Easy bruising?",
    bleedingStop: "Problems stopping bleeding?",

    gynekOpYn: "Have you had a gynecological surgical procedure?",
    otherOpYn: "Have you had other (non-gynecological) surgeries?",
    opProcedure: "Procedure / intervention",
    opDate: "Date",
    opReason: "Reason",
    opOutcome: "Outcome",

    geneticsYn: "Are there genetic or hereditary diseases in your family?",
    geneticsDetails: "Which diseases and which family member?",

    smoker: "Are you a smoker?",
    cigarettesPerDay: "How many cigarettes per day?",
    vaping: "Do you use e-cigarettes or vapes?",
    drugsYn: "Have you used drugs/psychoactive substances in the past 5 years?",
    drugsDetails: "Which?",
    alcohol: "Do you consume alcohol?",
    alcoholDrinks: "How many drinks per week? (1 drink = 0.5l beer / glass of wine / shot of spirits)",
    tattoosYn: "Do you have tattoos?",
    tattoosDetails: "Location, year and any complications",
    otherInfo: "Any other information you consider relevant",

    mPregYn: "Have you had a pregnancy with your current partner?",
    mPregDetails: "How many / how many full-term?",
    mOtherPregYn: "Have you had a pregnancy with another partner?",
    mOtherPregDetails: "How many / how many full-term?",
    klomidYn: "Have you used Clomid/Clomiphene?",
    klomidDur: "How long?",
    mArtYn: "Have you had infertility tests or ART (IUI, IVF, ICSI)?",
    mArtDetails: "Details",
    erectionYn: "Do you have difficulties with erection, maintaining erection, or ejaculation?",
    erectionDetails: "Details",
    testesYn: "Have you ever had undescended testes?",
    testesDetails: "Details",
    mumpsYn: "Did you have mumps in childhood?",
    mumpsEffect: "Did it affect the testes?",
    pubertyAge: "Age when puberty began?",
    saunaYn: "Do you use hot baths, saunas or jacuzzis?",
    saunaDetails: "How often and when was the last time?",
    feverYn: "Have you had a feverish illness in the last year?",
    feverDetails: "Period and temperature",
    steroidsYn: "Have you used anabolic steroids or bodybuilding drugs?",
    steroidsDetails: "Which, how long, when stopped?",

    sexFreq: "How often do you have intercourse?",
    sexFreqExample: "e.g. 2-3x per week",

    mSurgeryYn: "Have you had a surgical procedure?",

    mDrugsYn: "Have you used drugs in the past 5 years?",
  },
  opts: {
    married: "Married",
    unmarried: "Unmarried",
    email: "Email",
    phoneViber: "Phone/Viber",
    bothComm: "Both",
    positive: "Positive",
    negative: "Negative",
    maleFactor: "Male factor",
    femaleFactor: "Female factor",
    bothFactor: "Both",
  },
  diseases: [
    "Diabetes",
    "Asthma",
    "Tuberculosis",
    "Arrhythmias",
    "Chest pain",
    "High blood pressure",
    "Thyroid / endocrine disorders",
    "Congenital diseases",
    "Psychiatric condition / depression",
    "Liver diseases",
    "Gastrointestinal issues",
    "Kidney diseases",
    "Cancer (chemo/radiotherapy)",
    "Rheumatoid arthritis",
    "Immune disorders",
    "Neurological issues",
    "Coagulation / clotting issues",
    "Other infections",
    "Exposure to radioactive / toxic substances",
  ],
  email: {
    subjectPrefix: "[Questionnaire]",
    emailTitle: "Patient Questionnaire — Human Reproduction Center",
    receivedAt: "Received:",
    notAnswered: "not answered",
    notEntered: "not entered",
    none: "None",
    autoGenerated: "Auto-generated from humanreproduction.com/upitnik",
    patientSubject: "Confirmation — questionnaire received | Human Reproduction Center",
    patientGreeting: "Dear {name},",
    patientFallbackName: "patient",
    patientBody:
      "We have received your questionnaire. Our team will review your answers and contact you as soon as possible.",
    patientSignoff: "Thank you for your trust.",
  },
};

// ───────────────────────────────────────────────────────────────────────
// RUSSIAN — slobodno popunite (trenutno fallback na ME)
// ───────────────────────────────────────────────────────────────────────
const RU: QuestionnaireI18n = {
  ...ME,
  page: {
    eyebrow: "Human Reproduction Center",
    title: "Анкета для пациентов",
    intro:
      "Заполняя эту анкету, вы помогаете нашей команде лучше понять ваш случай и выявить детали, которые могут помочь в выборе правильного лечения.",
    confidential: "Все данные строго конфиденциальны",
  },
  ui: {
    ...ME.ui,
    yes: "Да",
    no: "Нет",
    submit: "Отправить анкету",
    submitting: "Отправка...",
    addRow: "Добавить строку",
    successTitle: "Анкета успешно отправлена!",
    successText: "Наша команда получила ваши ответы и свяжется с вами в ближайшее время. Спасибо!",
    errorText: "Произошла ошибка. Попробуйте ещё раз или свяжитесь с нами.",
    consent: "Заполняя и отправляя эту анкету, вы помогаете нам лучше понять ваш случай. Спасибо!",
  },
  email: {
    ...ME.email,
    subjectPrefix: "[Анкета]",
    emailTitle: "Анкета для пациентов — Human Reproduction Center",
    receivedAt: "Получено:",
    notAnswered: "нет ответа",
    notEntered: "не указано",
    none: "Нет",
    autoGenerated: "Автоматически с humanreproduction.com/upitnik",
    patientSubject: "Подтверждение — анкета получена | Human Reproduction Center",
    patientGreeting: "Уважаемый(ая) {name},",
    patientFallbackName: "пациент",
    patientBody:
      "Мы получили вашу анкету. Наша команда изучит ответы и свяжется с вами в ближайшее время.",
    patientSignoff: "Спасибо за доверие.",
  },
};

export const QUESTIONNAIRE_I18N: Record<Locale, QuestionnaireI18n> = {
  me: ME,
  en: EN,
  ru: RU,
};

export function getQuestionnaireI18n(locale: Locale): QuestionnaireI18n {
  return QUESTIONNAIRE_I18N[locale] ?? ME;
}
