import type { Locale } from "@/lib/i18n";
import { locales } from "@/lib/i18n";

/** Jedinstveni ključevi za `site_locale_strings.field_key`. */
export const SITE_STRING_KEYS = [
  "org.brand",
  "org.subtitle",
  "header.cta_book",
  /** Puno URL, ili sidro npr. #kontakt, ili /posts/slug (samo put; locale se dodaje u layoutu). */
  "header.cta_book_href",
  /** Mobilni meni / donji red — pretraga (npr. link na početnu ili tražilicu). */
  "header.nav_search_label",
  "header.nav_search_href",

  "hero.line1",
  "hero.line2",
  "hero.rotate.1",
  "hero.rotate.2",
  "hero.rotate.3",
  "hero.rotate.4",
  "hero.subtitle",
  "hero.cta_primary",
  "hero.cta_secondary",
  "hero.cta_primary_href",
  "hero.cta_secondary_href",

  "stat1.value",
  "stat1.label",
  "stat2.value",
  "stat2.label",
  "stat3.value",
  "stat3.label",
  "stat4.value",
  "stat4.label",

  "section.services_title",
  "section.services_subtitle",
  "section.about_title",
  "section.about_lead",
  "section.news_title",

  "home.news_eyebrow",
  "home.news_read_label",
  "home.cta_eyebrow",
  "home.cta_heading_line1",
  "home.cta_heading_line2",
  "home.hours_mon_fri_label",
  "home.hours_sat_sun_label",

  "team.eyebrow",
  "team.title",
  "team.lead",
  "team.cta",
  "team.m1.name",
  "team.m1.role",
  "team.m1.bio",
  "team.m2.name",
  "team.m2.role",
  "team.m3.name",
  "team.m3.role",
  "team.m4.name",
  "team.m4.role",
  "team.hl1.title",
  "team.hl1.body",
  "team.hl2.title",
  "team.hl2.body",
  "team.hl3.title",
  "team.hl3.body",

  "footer.tagline",
  "footer.col_clinic",
  "footer.col_about_nav",
  "footer.col_infertility",
  "footer.col_iui_ivf_nav",
  "footer.col_ginekologija_nav",
  "footer.col_trudnoca_nav",
  "footer.col_preservacija_nav",
  "footer.col_services_footer",
  "footer.col_contact",
  "footer.about_body",
  "footer.site_domain_label",
  "footer.site_domain_href",
  "footer.hours_title",
  "footer.nav_title",
  "footer.social_title",
  "footer.closed",
  "footer.copyright",
  "footer.crafted",
  "footer.crafted_by",
  "footer.privacy",
  "footer.terms",
  /** Putanje npr. /s/politika-privatnosti (locale se dodaje u layoutu). */
  "footer.privacy_href",
  "footer.terms_href",

  "contact.phone1",
  "contact.phone2",
  "contact.email",
  "contact.address",
  /** Link na Google mape za adresu u footeru. */
  "contact.maps_href",

  "social.facebook",
  "social.instagram",
  "social.youtube",
  "social.linkedin",

  "hours.mon_fri",
  "hours.tuesday",
  "hours.sat",
  "hours.sun",
] as const;

export type SiteStringKey = (typeof SITE_STRING_KEYS)[number];

export const SITE_STRING_LABELS: Record<SiteStringKey, string> = {
  "org.brand": "Naziv brenda (logo)",
  "org.subtitle": "Kratak opis ispod brenda",
  "header.cta_book": "Dugme u headeru (npr. Zakaži)",
  "header.cta_book_href": "URL / sidro za dugme u headeru (#kontakt ili https://…)",
  "header.nav_search_label": "Mobilni meni — tekst „Pretraga“",
  "header.nav_search_href": "Mobilni meni — link za pretragu (npr. / ili #)",

  "hero.line1": "Hero — prvi red naslova",
  "hero.line2": "Hero — drugi red / naglašeni",
  "hero.rotate.1": "Hero — rotirajući tekst 1 (banner)",
  "hero.rotate.2": "Hero — rotirajući tekst 2",
  "hero.rotate.3": "Hero — rotirajući tekst 3",
  "hero.rotate.4": "Hero — rotirajući tekst 4",
  "hero.subtitle": "Hero — podnaslov",
  "hero.cta_primary": "Hero — primarno dugme",
  "hero.cta_secondary": "Hero — sekundarno dugme",
  "hero.cta_primary_href": "Hero — link primarnog dugmeta",
  "hero.cta_secondary_href": "Hero — link sekundarnog dugmeta",

  "stat1.value": "Stat 1 — broj",
  "stat1.label": "Stat 1 — opis",
  "stat2.value": "Stat 2 — broj",
  "stat2.label": "Stat 2 — opis",
  "stat3.value": "Stat 3 — broj",
  "stat3.label": "Stat 3 — opis",
  "stat4.value": "Stat 4 — broj",
  "stat4.label": "Stat 4 — opis",

  "section.services_title": "Blok usluga — naslov",
  "section.services_subtitle": "Blok usluga — podnaslov",
  "section.about_title": "O nama — naslov",
  "section.about_lead": "O nama — uvod",
  "section.news_title": "Novosti / blog — naslov",

  "home.news_eyebrow": "Početna — eyebrow iznad bloga (npr. „Blog“)",
  "home.news_read_label": "Početna — tekst dugmeta na kartici članka (npr. „Pročitajte“)",
  "home.cta_eyebrow": "Početna CTA — mali naslov iznad (eyebrow)",
  "home.cta_heading_line1": "Početna CTA — prvi red naslova",
  "home.cta_heading_line2": "Početna CTA — drugi red naslova (kurziv)",
  "home.hours_mon_fri_label": "Početna CTA / kontakt — oznaka „Pon – Pet“",
  "home.hours_sat_sun_label": "Početna CTA / kontakt — oznaka „Sub – Ned“",

  "team.eyebrow": "Tim — mali naslov (iznad glavnog)",
  "team.title": "Tim — glavni naslov",
  "team.lead": "Tim — uvodni tekst",
  "team.cta": "Tim — tekst linka (npr. Upoznajte tim →)",
  "team.m1.name": "Član 1 — ime i prezime",
  "team.m1.role": "Član 1 — titula / uloga",
  "team.m1.bio": "Član 1 — kratki uvodni tekst (istaknut ispod fotografije)",
  "team.m2.name": "Član 2 — ime i prezime",
  "team.m2.role": "Član 2 — titula / uloga",
  "team.m3.name": "Član 3 — ime i prezime",
  "team.m3.role": "Član 3 — titula / uloga",
  "team.m4.name": "Član 4 — ime i prezime",
  "team.m4.role": "Član 4 — titula / uloga",
  "team.hl1.title": "Istaknuta stavka 1 — naslov",
  "team.hl1.body": "Istaknuta stavka 1 — tekst",
  "team.hl2.title": "Istaknuta stavka 2 — naslov",
  "team.hl2.body": "Istaknuta stavka 2 — tekst",
  "team.hl3.title": "Istaknuta stavka 3 — naslov",
  "team.hl3.body": "Istaknuta stavka 3 — tekst",

  "footer.tagline": "Footer — tekst ispod loga",
  "footer.col_clinic": "Footer — naslov kolone „O klinici“",
  "footer.col_about_nav": "Footer — naslov kolone „O nama“",
  "footer.col_infertility": "Footer — kolona „Infertilitet i sterilitet“",
  "footer.col_iui_ivf_nav": "Meni i footer — kolona „IVF“ (naslov u mega meniju i podnožju)",
  "footer.col_ginekologija_nav": "Footer — kolona „Ginekologija“",
  "footer.col_trudnoca_nav": "Footer — kolona „Trudnoća“",
  "footer.col_preservacija_nav": "Footer — kolona „Prezervacija fertilnosti“",
  "footer.col_services_footer": "Footer — kolona „Usluge“",
  "footer.col_contact": "Footer — kolona „Kontakt“",
  "footer.about_body": "Footer — uvodni tekst ispod naziva klinike (O klinici)",
  "footer.site_domain_label": "Footer — prikaz web adrese (npr. humanreproduction.com)",
  "footer.site_domain_href": "Footer — puni URL sajta (https://…)",
  "footer.hours_title": "Footer — naslov radno vrijeme",
  "footer.nav_title": "Footer — naslov navigacije",
  "footer.social_title": "Footer — naslov društvene mreže",
  "footer.closed": "Footer — tekst kad je zatvoreno",
  "footer.copyright": "Footer — tekst uz godinu (© …)",
  "footer.crafted": "Footer — „Digital eXperience“ uvod",
  "footer.crafted_by": "Footer — ime izrade",
  "footer.privacy": "Footer — link Politika privatnosti (label)",
  "footer.terms": "Footer — link Uslovi (label)",
  "footer.privacy_href": "Footer — putanja politike (/s/slug ili #)",
  "footer.terms_href": "Footer — putanja uslova (/s/slug ili #)",

  "contact.phone1": "Telefon 1",
  "contact.phone2": "Telefon 2",
  "contact.email": "Email",
  "contact.address": "Adresa (jedan red)",
  "contact.maps_href": "Google Maps URL za adresu (https://…)",

  "social.facebook": "Facebook — link (footer)",
  "social.instagram": "Instagram — link (footer)",
  "social.youtube": "YouTube — link (footer, kanal ili video)",
  "social.linkedin": "LinkedIn — link (footer)",

  "hours.mon_fri": "Radno vrijeme Ponedjeljak–Petak",
  "hours.tuesday": "Utorak (ako različito)",
  "hours.sat": "Subota",
  "hours.sun": "Nedjelja",
};

type Defaults = Record<Locale, Record<SiteStringKey, string>>;

/** Početni sadržaj inspirišan humanom reprodukcijom / prezentacionim kliničkim sajtom. */
const ME_SITE_STRING_DEFAULTS = {
    "org.brand": "Human Reproduction Center Budva",
    "org.subtitle": "Centar za humanu reprodukciju",
    "header.cta_book": "Zakaži pregled",
    "header.cta_book_href": "#kontakt",
    "header.nav_search_label": "Pretraga",
    "header.nav_search_href": "/",

    "hero.line1": "Gdje život počinje",
    "hero.line2": "savremena reproduktivna medicina",
    "hero.rotate.1": "Savremena tehnologija i laboratorij",
    "hero.rotate.2": "Stručnjaci posvećeni vašem rezultatu",
    "hero.rotate.3": "Iskustvo na kojem možete računati",
    "hero.rotate.4": "Njega i poverenje na prvom mjestu",
    "hero.subtitle":
      "Napredna reproduktivna medicina za vašu porodicu. Individualizovan pristup i savremena oprema.",
    "hero.cta_primary": "Zakaži pregled",
    "hero.cta_secondary": "Naše usluge",
    "hero.cta_primary_href": "#kontakt",
    "hero.cta_secondary_href": "#usluge",

    "stat1.value": "98%",
    "stat1.label": "Godišnja stopa zadovoljstva pacijenata",
    "stat2.value": "1000+",
    "stat2.label": "Rođene djece u našoj misiji",
    "stat3.value": "5000+",
    "stat3.label": "Tretiranih pacijenata",
    "stat4.value": "15+",
    "stat4.label": "Specijalista u multidisciplinarnom timu",

    "section.services_title": "Tretmani i opcije",
    "section.services_subtitle":
      "Sveobuhvatna medicinska njega u jednoj ustanovi, od dijagnostike do tretmana i pratnje.",
    "section.about_title": "Naša priča",
    "section.about_lead":
      "Posvećeni ste najnovijim dostignućima u reproduktivnoj medicini uz human pristup i jasnu komunikaciju.",
    "section.news_title": "Novosti iz centra i nauke",

    "home.news_eyebrow": "Blog",
    "home.news_read_label": "Pročitajte",
    "home.cta_eyebrow": "Vaš put počinje ovdje",
    "home.cta_heading_line1": "Zakažite konsultaciju",
    "home.cta_heading_line2": "s našim stručnjacima",
    "home.hours_mon_fri_label": "Pon – Pet",
    "home.hours_sat_sun_label": "Sub – Ned",

    "team.eyebrow": "Naš tim",
    "team.title": "Dr Tatjana Motrenko Simić i multidisciplinarni tim uz vas",
    "team.lead":
      "Vođa kliničkog tima je dr Tatjana Motrenko Simić, specijalistkinja ginekologije i akušerstva. Uz nju multidisciplinarni tim — laboratorij i embriologija — vodi vas kroz cjelokupan put, od prve konsultacije do jasnog plana i diskretne podrške.",
    "team.cta": "Upoznajte tim",
    "team.m1.name": "Dr Tatjana Motrenko Simić",
    "team.m1.role": "Specijalista ginekologije i akušerstva",
    "team.m1.bio":
      "Iskusna je u ginekologiji, akušerstvu i reproduktivnoj medicini, s naglaskom na jasnu komunikaciju i individualan plan za svaki par. Vodi rad u centru uz pažljiv pristup i koordinaciju sa laboratorijem i embriologijom.",
    "team.m2.name": "Dr [Ime i prezime]",
    "team.m2.role": "Specijalista ginekologije i akušerstva",
    "team.m3.name": "Dr [Ime i prezime]",
    "team.m3.role": "Specijalista kliničke embriologije",
    "team.m4.name": "Dr [Ime i prezime]",
    "team.m4.role": "Specijalistički saradnik",
    "team.hl1.title": "Individualan pristup",
    "team.hl1.body": "Plan prilagođen vašim potrebama i tempu.",
    "team.hl2.title": "Savremena dijagnostika",
    "team.hl2.body": "Laboratorij i protokoli po međunarodnim smjernicama.",
    "team.hl3.title": "Diskrecija i podrška",
    "team.hl3.body": "Prostor osmišljen da se osjećate sigurno.",

    "footer.tagline":
      "Posvećeni vašem zdravlju uz savremenu medicinsku njegu i individualizovan pristup od 2004. godine.",
    "footer.col_clinic": "O klinici",
    "footer.col_about_nav": "O nama",
    "footer.col_infertility": "Infertilitet i sterilitet",
    "footer.col_iui_ivf_nav": "IVF",
    "footer.col_ginekologija_nav": "Ginekologija",
    "footer.col_trudnoca_nav": "Trudnoća",
    "footer.col_preservacija_nav": "Prezervacija fertilnosti",
    "footer.col_services_footer": "Usluge",
    "footer.col_contact": "Kontakt",
    "footer.about_body":
      "Centar za humanu reprodukciju Budva pruža stručnu podršku parovima na putu ka roditeljstvu kroz dijagnostiku, ginekologiju, IUI, IVF i savremene metode liječenja infertiliteta.",
    "footer.site_domain_label": "humanreproduction.com",
    "footer.site_domain_href": "https://humanreproduction.com",
    "footer.hours_title": "Radno vrijeme",
    "footer.nav_title": "Navigacija",
    "footer.social_title": "Pratite nas",
    "footer.closed": "Zatvoreno",
    "footer.copyright": "Centar za humanu reprodukciju Budva. Sva prava zadržana.",
    "footer.crafted": "DigitaL eXperience",
    "footer.crafted_by": "Computer Doctor Podgorica",
    "footer.privacy": "Politika privatnosti",
    "footer.terms": "Uslovi korišćenja",
    "footer.privacy_href": "/s/politika-privatnosti",
    "footer.terms_href": "/s/uslovi-koriscenja",

    "contact.phone1": "+382 67 052 052",
    "contact.phone2": "067 052 052",
    "contact.email": "info@humanareprodukcija.com",
    "contact.address": "bb XVI Ulica, Budva 85310",
    "contact.maps_href": "https://maps.app.goo.gl/XRLPBsA1YMM4vaX38",

    "social.facebook": "https://facebook.com",
    "social.instagram": "https://instagram.com",
    "social.youtube": "",
    "social.linkedin": "",

    "hours.mon_fri": "08:00 – 20:00",
    "hours.tuesday": "08:00 – 20:00",
    "hours.sat": "Zatvoreno",
    "hours.sun": "Zatvoreno",
} satisfies Record<SiteStringKey, string>;

/** EN i RU počinju kao kopija ME dok CMS ne dobije posebne prevode (fallback na javnom sajtu). */
export const SITE_STRING_DEFAULTS: Defaults = {
  me: ME_SITE_STRING_DEFAULTS,
  en: {
    ...ME_SITE_STRING_DEFAULTS,
    "hero.cta_secondary": "Our services",
    "hero.cta_secondary_href": "#usluge",
  },
  ru: {
    ...ME_SITE_STRING_DEFAULTS,
    "hero.cta_secondary": "Наши услуги",
    "hero.cta_secondary_href": "#usluge",
  },
};

export function allSiteStringKeys(): SiteStringKey[] {
  return [...SITE_STRING_KEYS];
}

export function localesList(): readonly Locale[] {
  return locales;
}

/** Grupe polja za admin „Sadržaj stranica“ (jedna forma, tabovi po jeziku). */
export const SITE_STRING_GROUPS = {
  headerFooter: [
    "org.brand",
    "org.subtitle",
    "header.cta_book",
    "header.cta_book_href",
    "header.nav_search_label",
    "header.nav_search_href",
    "footer.tagline",
    "footer.col_clinic",
    "footer.col_about_nav",
    "footer.col_infertility",
    "footer.col_iui_ivf_nav",
    "footer.col_ginekologija_nav",
    "footer.col_trudnoca_nav",
    "footer.col_preservacija_nav",
    "footer.col_services_footer",
    "footer.col_contact",
    "footer.about_body",
    "footer.site_domain_label",
    "footer.site_domain_href",
    "footer.hours_title",
    "footer.nav_title",
    "footer.social_title",
    "footer.closed",
    "footer.copyright",
    "footer.crafted",
    "footer.crafted_by",
    "footer.privacy",
    "footer.terms",
    "footer.privacy_href",
    "footer.terms_href",
    "contact.phone1",
    "contact.phone2",
    "contact.email",
    "contact.address",
    "contact.maps_href",
    "hours.mon_fri",
    "hours.tuesday",
    "hours.sat",
    "hours.sun",
  ] as const satisfies readonly SiteStringKey[],

  hero: [
    "hero.line1",
    "hero.line2",
    "hero.rotate.1",
    "hero.rotate.2",
    "hero.rotate.3",
    "hero.rotate.4",
    "hero.subtitle",
    "hero.cta_primary",
    "hero.cta_secondary",
    "hero.cta_primary_href",
    "hero.cta_secondary_href",
  ] as const satisfies readonly SiteStringKey[],

  sections: [
    "stat1.value",
    "stat1.label",
    "stat2.value",
    "stat2.label",
    "stat3.value",
    "stat3.label",
    "stat4.value",
    "stat4.label",
    "section.services_title",
    "section.services_subtitle",
    "section.about_title",
    "section.about_lead",
    "section.news_title",
    "home.news_eyebrow",
    "home.news_read_label",
    "home.cta_eyebrow",
    "home.cta_heading_line1",
    "home.cta_heading_line2",
    "home.hours_mon_fri_label",
    "home.hours_sat_sun_label",
  ] as const satisfies readonly SiteStringKey[],

  team: [
    "team.eyebrow",
    "team.title",
    "team.lead",
    "team.cta",
    "team.m1.name",
    "team.m1.role",
    "team.m1.bio",
    "team.m2.name",
    "team.m2.role",
    "team.m3.name",
    "team.m3.role",
    "team.m4.name",
    "team.m4.role",
  ] as const satisfies readonly SiteStringKey[],

  /** Footer — društvene mreže (prazan URL = link se ne prikazuje). */
  social: [
    "social.facebook",
    "social.instagram",
    "social.youtube",
    "social.linkedin",
  ] as const satisfies readonly SiteStringKey[],
} as const;

/** URL ključevi — prazan string u bazi znači „namjerno skriveno“, ne fallback na default. */
export const SOCIAL_URL_KEYS = SITE_STRING_GROUPS.social;

export type SiteStringGroupId = keyof typeof SITE_STRING_GROUPS;
