"use server";

import { redirect } from "next/navigation";

import { adminPath } from "@/lib/admin-base-path";
import { getSession, hasPermission, PERMISSIONS } from "@/lib/auth";
import { DEFAULT_NOTIFY_INBOX } from "@/lib/email/resolve-notify-inbox";
import { sendResendEmail } from "@/lib/email/send-resend-email";
import type { Locale } from "@/lib/i18n";
import {
  isMachineTranslateConfigured,
  machineTranslateTexts,
} from "@/lib/machine-translate";
import {
  getQuestionnaireI18n,
  type QuestionnaireI18n,
} from "@/lib/questionnaire-i18n";
import {
  deleteQuestionnaireOverride,
  invalidateQuestionnaireOverrideCache,
  saveQuestionnaireOverride,
} from "@/lib/questionnaire-overrides";
import { revalidatePath } from "next/cache";

export async function sendTestQuestionnaireEmailAction(): Promise<void> {
  const session = await getSession();
  if (!session) redirect(adminPath("login"));
  if (!hasPermission(session.role, PERMISSIONS.SITE_CONTENT_MANAGE)) {
    redirect(adminPath());
  }

  const t = getQuestionnaireI18n("me");
  const to = process.env.UPITNIK_NOTIFY_EMAIL?.trim() || DEFAULT_NOTIFY_INBOX;
  const now = new Date().toLocaleString("sr-ME", { timeZone: "Europe/Podgorica" });

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
  <body style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;padding:20px;color:#1a1a1a;background:#fff">
    <div style="background:#e8682a;color:#fff;padding:18px 24px;border-radius:8px;margin-bottom:20px">
      <h1 style="margin:0;font-size:18px">${t.email.emailTitle} — TEST</h1>
      <p style="margin:6px 0 0;font-size:13px;opacity:0.85">${t.email.receivedAt} ${now}</p>
    </div>
    <p style="font-size:14px;line-height:1.6">Ovo je <strong>probna poruka</strong> poslata iz admin panela.</p>
    <p style="font-size:14px;line-height:1.6">Ako vidite ovu poruku — email pipeline radi ispravno i pacijenti će uspešno slati upitnik.</p>
    <hr style="margin-top:24px;border:1px solid #f0e6dc">
    <p style="font-size:11px;color:#999;margin-top:8px">${t.email.autoGenerated}</p>
  </body></html>`;

  const result = await sendResendEmail({
    to,
    subject: `${t.email.subjectPrefix} TEST iz admin panela — ${new Date().toLocaleDateString("sr-ME")}`,
    text: "Test poruka iz admin panela. Email pipeline radi.",
    html,
    logPrefix: "[upitnik-admin-test]",
  });

  const params = new URLSearchParams();
  if (result.ok) {
    params.set("ok", "1");
    params.set("to", to);
  } else {
    params.set("err", "code" in result ? result.code : "unknown");
  }
  redirect(adminPath(`upitnik?${params.toString()}`));
}

/**
 * Sakuplja sve stringove iz QuestionnaireI18n strukture u flat listu.
 * Vraća parove [path, vrijednost] gdje je path "f.fullName", "sections.s1" itd.
 */
function flattenI18n(obj: QuestionnaireI18n): Array<{ path: string; value: string }> {
  const out: Array<{ path: string; value: string }> = [];

  const walk = (node: unknown, prefix: string): void => {
    if (typeof node === "string") {
      out.push({ path: prefix, value: node });
    } else if (Array.isArray(node)) {
      for (let i = 0; i < node.length; i++) {
        walk(node[i], `${prefix}[${i}]`);
      }
    } else if (node && typeof node === "object") {
      for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
        walk(v, prefix ? `${prefix}.${k}` : k);
      }
    }
  };

  walk(obj, "");
  return out;
}

/** Konstruiše JSON override od flat liste prevoda. */
function buildOverrideFromFlat(items: Array<{ path: string; value: string }>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const { path, value } of items) {
    const parts = path.split(/\.|\[/).filter(Boolean).map((p) => p.replace(/\]$/, ""));
    let node: Record<string, unknown> = out;
    for (let i = 0; i < parts.length - 1; i++) {
      const key = parts[i]!;
      const next = parts[i + 1]!;
      const isNextArr = /^\d+$/.test(next);
      if (!(key in node)) node[key] = isNextArr ? [] : {};
      node = node[key] as Record<string, unknown>;
    }
    const last = parts[parts.length - 1]!;
    if (/^\d+$/.test(last)) {
      (node as unknown as unknown[])[Number(last)] = value;
    } else {
      node[last] = value;
    }
  }
  return out;
}

export type AutoTranslateResult = {
  ok: boolean;
  count?: number;
  error?: string;
};

/** Pokreće AI prevod ME → EN ili ME → RU i upisuje override u bazu. */
export async function autoTranslateQuestionnaireAction(
  target: "en" | "ru",
): Promise<AutoTranslateResult> {
  const session = await getSession();
  if (!session) return { ok: false, error: "Niste prijavljeni." };
  if (!hasPermission(session.role, PERMISSIONS.SITE_CONTENT_MANAGE)) {
    return { ok: false, error: "Nemate dozvolu." };
  }
  if (!isMachineTranslateConfigured()) {
    return { ok: false, error: "AI prevod nije podešen u .env (TRANSLATE_PROVIDER + API ključ)." };
  }

  const source = getQuestionnaireI18n("me");
  const flat = flattenI18n(source);

  try {
    const translated = await machineTranslateTexts(
      flat.map((x) => x.value),
      target,
    );

    const items = flat.map((x, i) => ({
      path: x.path,
      value: translated[i] || x.value,
    }));

    const override = buildOverrideFromFlat(items);
    await saveQuestionnaireOverride(target as Locale, override as Parameters<typeof saveQuestionnaireOverride>[1]);
    invalidateQuestionnaireOverrideCache();
    revalidatePath(`/${target}/upitnik`);

    return { ok: true, count: items.length };
  } catch (e) {
    console.error("[upitnik AI translate] failed:", e);
    return {
      ok: false,
      error: e instanceof Error ? e.message : "Nepoznata greška.",
    };
  }
}

/** Briše override (vraća na fajl defaulte). */
export async function resetQuestionnaireOverrideAction(target: Locale): Promise<void> {
  const session = await getSession();
  if (!session) redirect(adminPath("login"));
  if (!hasPermission(session.role, PERMISSIONS.SITE_CONTENT_MANAGE)) {
    redirect(adminPath());
  }
  await deleteQuestionnaireOverride(target);
  revalidatePath(`/${target}/upitnik`);
  redirect(adminPath(`upitnik?reset=${target}`));
}
